### ISSUE TITLE
Can I create a join relation based on two possible columns?

### ISSUE THREAD

**Issue by claudiomramirez** [Vincit/objection.js#650]
Sorry if the title is not to clear but I wasn't sure how to put it simple. I came across a somewhat odd situation where I can have 2 categories, each with its own list of products, but if category number 1 is associated to category number 2, I need to get the list of products associated to both categories.

My tables are somthing like this:

```
category:
  id: primary key
  associated_category_id: foreign key that references category

product:
  id: primary key
  category_id: foreign key that references category
```

In my category model, I had this relation defined:
```
products: {
  relation: Model.HasManyRelation,
  modelClass: 'Product',
        join: {
          from: `product.category_id`,
          to: `category.id`,
        },
},
```

But what I really need now, is something like this:
```
products: {
  relation: Model.HasManyRelation,
  modelClass: 'Product',
        join: {
          from: `product.category_id`,
          to: `category.id` OR `category.associated_category_id`,
        },
},
```

In pure SQL, it would be simple:
```
SELECT * 
FROM category INNER JOIN product on category.id = product.category_id OR category.related_category_id = product.category_id
WHERE box.category.id = {some id};
```
Is there a way to achive this, either using filter or modify?
